/*
 * Phellipe - GUI layout and Cairo painting for the voronoi-mosaic UI.
 *
 * Bold flat-color faceted mosaic, no gradients/skeuomorphism: a real bounded
 * Voronoi tessellation (see VoronoiGeometry.hpp, generated by
 * tools/gen_voronoi.py) divides the window into a central artwork cell,
 * several functional module cells (each a knob-row panel, same widget
 * language as paintKnob() below), and unlabeled dark filler facets for
 * texture.
 */

#pragma once

#include <cairo.h>

#include <cmath>
#include <cstdio>
#include <cstring>
#include <initializer_list>
#include <utility>
#include <vector>
#include <array>
#include <algorithm>

#include "../Params.hpp"
#include "VoronoiGeometry.hpp"
#include "PortraitAsset.hpp"

namespace phellipe {
namespace ui {

// -----------------------------------------------------------------------------------------------------------
// palette

struct Color { double r, g, b; };

inline constexpr Color fromHex(uint32_t rgb) noexcept
{
    return Color{ ((rgb >> 16) & 0xFF) / 255.0, ((rgb >> 8) & 0xFF) / 255.0, (rgb & 0xFF) / 255.0 };
}

static constexpr Color kBg        { 0.059, 0.035, 0.031 }; // #0f0908
static constexpr Color kTextMain  { 0.94, 0.90, 0.855 };   // #f0e6da
static constexpr Color kTextDim   { 0.60, 0.55, 0.51 };
static constexpr Color kAccent    { 0.910, 0.576, 0.353 }; // #e8935a
static constexpr Color kKnobBody  { 0.00, 0.00, 0.00 };
static constexpr Color kKnobRing  { 0.94, 0.90, 0.855 };
static constexpr Color kBtnBg     { 0.114, 0.110, 0.235 };

// -----------------------------------------------------------------------------------------------------------
// layout model

struct Knob
{
    uint32_t param;
    float cx, cy, radius;
    const char* label;
    Color accent;
};

struct Button { float x, y, w, h; const char* label; Color accent; };

struct PresetBarLayout
{
    Button prev, next, save, del;
    float nameX, nameY, nameW, nameH;
    Color accent;
};

// the semi-modular patch matrix: mirrors PhellipePlugin.cpp's Src/Dest enums
// exactly (both ultimately mirror the source-major patch_<src>_<dest> block
// in Params.hpp) - keep all three in sync.
enum PatchSrc { PatchSrcDrift = 0, PatchSrcAmpEnv, PatchSrcFilterEnv, PatchSrcLfo, PatchSrcModWheel, PatchSrcPitchBend,
                PatchSrcVelocity, PatchSrcAftertouch, kPatchNumSources };
enum PatchDest { PatchDestPitch = 0, PatchDestCutoff, PatchDestWave, PatchDestDelayTime, PatchDestChorusRate, PatchDestLfoRate, PatchDestAge,
                 PatchDestOscBFree, PatchDestOscCFree, PatchDestResonance, PatchDestDrive, PatchDestChorusDepth, PatchDestSpaceSize,
                 PatchDestDelayMix, PatchDestNoise, kPatchNumDests };

static constexpr float kJackRadius = 7.0f;

struct Jack { float cx = 0.0f, cy = 0.0f; int index = -1; };

struct Layout
{
    float width, height;
    std::vector<Knob> knobs;
    PresetBarLayout presetBar;
    std::array<Jack, kPatchNumSources> sourceJacks; // indexed by PatchSrc
    std::array<Jack, kPatchNumDests> destJacks;      // indexed by PatchDest
};

// -----------------------------------------------------------------------------------------------------------
// layout builder

inline void addKnobRow(std::vector<Knob>& knobs, float rowCenterX, float rowW, float rowY, float radius,
                        Color accent, const std::vector<std::pair<uint32_t, const char*>>& items)
{
    const float rowX = rowCenterX - rowW / 2.0f;
    const float slot = rowW / (float)items.size();
    size_t i = 0;
    for (const auto& item : items)
    {
        const float cx = rowX + slot * ((float)i + 0.5f);
        knobs.push_back({ item.first, cx, rowY, radius, item.second, accent });
        ++i;
    }
}

struct CellPolygonBounds { float x, y, w, h, cx, cy; };

inline CellPolygonBounds boundsOf(const VoronoiCellGeo& cell) noexcept
{
    float minX = cell.polygon[0].first, maxX = minX;
    float minY = cell.polygon[0].second, maxY = minY;
    for (const auto& p : cell.polygon)
    {
        minX = std::min(minX, p.first);  maxX = std::max(maxX, p.first);
        minY = std::min(minY, p.second); maxY = std::max(maxY, p.second);
    }
    return { minX, minY, maxX - minX, maxY - minY, (minX + maxX) * 0.5f, (minY + maxY) * 0.5f };
}

// one row of knobs within a cell - most cells have exactly one (subLabel
// nullptr); CORE has three (the shared unison row, then one per additional
// tunable oscillator, each with its own small sub-label).
struct KnobRowSpec
{
    const char* subLabel; // nullptr = no sub-label drawn above this row
    std::vector<std::pair<uint32_t, const char*>> knobs;
};

// per-functional-cell content: title/subtitle/knob row(s), anchored at the
// cell's polygon-bbox center plus a hand-tuned (dx,dy) nudge - checked
// visually against this exact geometry (see tools/gen_voronoi.py) so it's
// known to clear each polygon's edges.
struct CellContent
{
    const char* tag;
    const char* title;
    const char* subtitle;
    float titleSize;
    float dx, dy;
    float knobRadius;
    float rowWidth;
    float rowSpacing; // vertical distance between successive knob rows
    float rowDxStep = 0.0f; // extra rightward shift per row index - the
                             // polygon's left edge can encroach further at
                             // lower rows (e.g. CORE's hexagon narrows
                             // toward its bottom-left corner), so later rows
                             // need to sit further right to stay clear of it
    std::vector<KnobRowSpec> rows;
};

inline const std::vector<CellContent>& cellContents()
{
    static const std::vector<CellContent> contents = {
        { "core",      "CORE",      "OSCILLATOR STACK", 21.0f,  6.0f, -90.0f, 14.0f, 170.0f, 84.0f, 15.0f,
          {
              { nullptr, { { kParamVoices, "VOICES" }, { kParamDetune, "DETUNE" }, { kParamSpread, "SPREAD" }, { kParamOscALevel, "LEVEL" }, { kParamWave, "WAVE" } } },
              { "OSC B", { { kParamOscBOctave, "OCT" }, { kParamOscBSemi, "SEMI" }, { kParamOscBWave, "WAVE" }, { kParamOscBLevel, "LEVEL" }, { kParamOscBFree, "FREE" } } },
              { "OSC C", { { kParamOscCOctave, "OCT" }, { kParamOscCSemi, "SEMI" }, { kParamOscCWave, "WAVE" }, { kParamOscCLevel, "LEVEL" }, { kParamOscCFree, "FREE" } } },
          } },
        { "resonator", "RESONATOR", "FILTER + BODY",     21.0f,  10.0f,  -8.0f, 18.0f, 215.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamCutoff, "CUTOFF" }, { kParamResonance, "RESO" }, { kParamDrive, "DRIVE" } } } } },
        { "drift",     "DRIFT",     "SLOW MODULATION",   19.0f,  -8.0f,   4.0f, 17.0f, 160.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamDriftRate, "RATE" }, { kParamDriftDepth, "DEPTH" }, { kParamDriftChaos, "CHAOS" } } } } },
        { "grain",     "GRAIN",     "TEXTURE + NOISE",   19.0f, -14.0f,  62.0f, 17.0f, 175.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamNoise, "NOISE" }, { kParamGrain, "GRAIN" }, { kParamAge, "AGE" } } } } },
        { "space",     "SPACE",     "REVERB",             19.0f,   6.0f,  10.0f, 17.0f, 160.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamSpaceSize, "SIZE" }, { kParamSpaceDecay, "DECAY" }, { kParamSpaceMix, "MIX" } } } } },
        // "output" now lives in the small polygon that used to be FillF
        // (unlabeled filler) - swapped with "modwheel" below since MOD
        // WHEEL's two source rows didn't fit its old cramped triangle-ish
        // home but fit easily in OUTPUT's old, more generous one.
        { "output",    "OUTPUT",    "MASTER",            16.0f,   0.0f,   0.0f, 14.0f,  95.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamVolume, "VOLUME" }, { kParamWidth, "WIDTH" } } } } },
        { "ampenv",    "AMP ENV",   "SWELL SHAPE",       19.0f,   0.0f, -40.0f, 16.0f, 190.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamAmpAttack, "ATTACK" }, { kParamAmpDecay, "DECAY" }, { kParamAmpSustain, "SUSTAIN" }, { kParamAmpRelease, "RELEASE" } } } } },
        { "filterenv", "FILTER ENV","CUTOFF ENVELOPE",   19.0f,   0.0f,   0.0f, 15.0f, 180.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamFilterAttack, "ATTACK" }, { kParamFilterDecay, "DECAY" }, { kParamFilterSustain, "SUSTAIN" }, { kParamFilterRelease, "RELEASE" } } } } },
        { "delay",     "DELAY",     "PING-PONG ECHO",     19.0f,   0.0f,   0.0f, 15.0f, 250.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamDelayTime, "TIME" }, { kParamDelayFeedback, "FEEDBACK" }, { kParamDelayMix, "MIX" }, { kParamDelaySync, "SYNC" } } } } },
        { "chorus",    "CHORUS",    "ENSEMBLE DRIFT",     19.0f,   0.0f,   0.0f, 16.0f, 190.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamChorusRate, "RATE" }, { kParamChorusDepth, "DEPTH" }, { kParamChorusMix, "MIX" } } } } },
        { "lfo",       "LFO",       "SINE, SLOW MOD",     16.0f,   0.0f,   0.0f, 13.0f,  50.0f, 0.0f, 0.0f,
          { { nullptr, { { kParamLfoRate, "RATE" } } } } },
        // "modwheel" now lives in the polygon that used to be "output" (see
        // the comment above the "output" entry) - a much roomier quad, so
        // both rows get a bigger radius/spacing than the old cramped home.
        { "modwheel",  "MOD WHEEL", "MIDI CC1",           15.0f,   0.0f, -20.0f, 13.0f,  50.0f, 70.0f, 0.0f,
          {
              { nullptr,     { { kParamModWheelAmount, "AMOUNT" } } },
              { "VELOCITY",  { { kParamVelocityAmount, "AMOUNT" } } },
          } },
        // pitchbend's polygon is a thin triangle - its bbox center sits close
        // to the top edge, so anchor at the true (vertex-average) centroid
        // instead: dx/dy below shift the bbox-center-relative anchor there.
        // The triangle widens toward its right vertex (y~347 locally), which
        // is exactly where the second row sits, so both rows have plenty of
        // width despite the cell's narrow overall footprint.
        { "pitchbend", "PITCH BEND","MIDI PB, -> TUNE",   13.0f, -31.0f,  25.0f, 11.0f,  40.0f, 75.0f, 0.0f,
          {
              { nullptr,       { { kParamPitchBendAmount, "AMOUNT" } } },
              { "AFTERTOUCH",  { { kParamAftertouchAmount, "AMOUNT" } } },
          } },
    };
    return contents;
}

inline Layout buildLayout(float width, float height)
{
    Layout L;
    L.width = width;
    L.height = height;

    // --- header: wordmark + preset bar, above the voronoi field ---
    // left-to-right: wordmark/subtitle, then prev/next, then the name field
    // filling the middle, then save/delete flush right (same convention as
    // Sideous's preset bar).
    {
        const float margin = 20.0f;
        const float h = 30.0f;
        const float y = (kVoronoiHeaderHeight - h) * 0.5f;
        const float barLeftX = 420.0f;
        const float barRightX = width - margin;

        L.presetBar.accent = kAccent;
        L.presetBar.prev = { barLeftX,              y, 30.0f, h, "<", kAccent };
        L.presetBar.next = { barLeftX + 30.0f + 8.0f, y, 30.0f, h, ">", kAccent };

        L.presetBar.del  = { barRightX - 70.0f,          y, 70.0f, h, "DELETE", kAccent };
        L.presetBar.save = { L.presetBar.del.x - 8.0f - 60.0f, y, 60.0f, h, "SAVE", kAccent };

        L.presetBar.nameX = L.presetBar.next.x + 30.0f + 14.0f;
        L.presetBar.nameY = y;
        L.presetBar.nameW = L.presetBar.save.x - 14.0f - L.presetBar.nameX;
        L.presetBar.nameH = h;
    }

    // --- voronoi field: one knob row per tagged functional cell ---
    for (const VoronoiCellGeo& cell : voronoiCells())
    {
        if (cell.label == nullptr)
            continue;

        const CellContent* content = nullptr;
        for (const CellContent& c : cellContents())
        {
            if (std::strcmp(c.tag, cell.label) == 0)
            {
                content = &c;
                break;
            }
        }
        if (content == nullptr)
            continue;

        const CellPolygonBounds b = boundsOf(cell);
        const float centerX = b.cx + content->dx;
        const float centerY = b.cy + content->dy + kVoronoiHeaderHeight;

        for (size_t r = 0; r < content->rows.size(); ++r)
        {
            const float rowY = centerY + 20.0f + content->rowSpacing * (float)r;
            const float rowCenterX = centerX + content->rowDxStep * (float)r;
            addKnobRow(L.knobs, rowCenterX, content->rowWidth, rowY, content->knobRadius, kAccent, content->rows[r].knobs);
        }

        // --- patch matrix: jacks, and (for AMP ENV/FILTER ENV/LFO) a small
        // compact attenuator knob living right at the source jack rather
        // than in the main knob row - see the PatchSrc/PatchDest enums
        // above. DRIFT reuses its existing DEPTH knob as its attenuator.
        auto knobCenter = [&L](uint32_t param, float& cx, float& cy) noexcept {
            for (const Knob& k : L.knobs)
                if (k.param == param) { cx = k.cx; cy = k.cy; return true; }
            return false;
        };

        if (std::strcmp(cell.label, "drift") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamDriftDepth, kx, ky))
                L.sourceJacks[PatchSrcDrift] = { kx + content->knobRadius + 12.0f, ky, PatchSrcDrift };
        }
        else if (std::strcmp(cell.label, "ampenv") == 0)
        {
            const float attX = centerX;
            const float attY = centerY + 20.0f + content->knobRadius + 48.0f;
            L.knobs.push_back({ kParamAmpEnvAmount, attX, attY, 10.0f, "AMT", kAccent });
            L.sourceJacks[PatchSrcAmpEnv] = { attX + 22.0f, attY, PatchSrcAmpEnv };
        }
        else if (std::strcmp(cell.label, "filterenv") == 0)
        {
            const float attX = centerX;
            const float attY = centerY + 20.0f + content->knobRadius + 48.0f;
            L.knobs.push_back({ kParamFilterEnvAmount, attX, attY, 10.0f, "AMT", kAccent });
            L.sourceJacks[PatchSrcFilterEnv] = { attX + 22.0f, attY, PatchSrcFilterEnv };
        }
        else if (std::strcmp(cell.label, "lfo") == 0)
        {
            float kx, ky;
            knobCenter(kParamLfoRate, kx, ky);
            const float attX = kx + content->knobRadius + 26.0f;
            L.knobs.push_back({ kParamLfoAmount, attX, ky, 10.0f, "AMT", kAccent });
            L.sourceJacks[PatchSrcLfo] = { attX + 22.0f, ky, PatchSrcLfo };
            L.destJacks[PatchDestLfoRate] = { kx - content->knobRadius - 12.0f, ky, PatchDestLfoRate };
        }
        else if (std::strcmp(cell.label, "core") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamWave, kx, ky))
                L.destJacks[PatchDestWave] = { kx + content->knobRadius + 12.0f, ky, PatchDestWave };
            L.destJacks[PatchDestPitch] = { centerX + 78.0f, centerY - 46.0f, PatchDestPitch };
            if (knobCenter(kParamOscBFree, kx, ky))
                L.destJacks[PatchDestOscBFree] = { kx + content->knobRadius + 12.0f, ky, PatchDestOscBFree };
            if (knobCenter(kParamOscCFree, kx, ky))
                L.destJacks[PatchDestOscCFree] = { kx + content->knobRadius + 12.0f, ky, PatchDestOscCFree };

            // FM matrix: 6 compact knobs in the cell's open right-side area
            // (this polygon is unusually wide - see tools/gen_voronoi.py -
            // so there's real room past the tuning rows' own jacks without
            // touching any other cell), each row vertically aligned with
            // that oscillator's own tuning row above. Positions hand-tuned
            // against this exact geometry, same as every other custom
            // placement in this file.
            const float fmRadius = 11.0f;
            const float fmCol1 = centerX + 136.0f;
            const float fmCol2 = centerX + 169.0f;
            const float rowAY = centerY + 20.0f;
            const float rowBY = rowAY + content->rowSpacing;
            const float rowCY = rowAY + content->rowSpacing * 2.0f;

            L.knobs.push_back({ kParamFmAtoB, fmCol1, rowAY, fmRadius, "A>B", kAccent });
            L.knobs.push_back({ kParamFmAtoC, fmCol2, rowAY, fmRadius, "A>C", kAccent });
            L.knobs.push_back({ kParamFmBtoA, fmCol1, rowBY, fmRadius, "B>A", kAccent });
            L.knobs.push_back({ kParamFmBtoC, fmCol2, rowBY, fmRadius, "B>C", kAccent });
            L.knobs.push_back({ kParamFmCtoA, fmCol1, rowCY, fmRadius, "C>A", kAccent });
            L.knobs.push_back({ kParamFmCtoB, fmCol2, rowCY, fmRadius, "C>B", kAccent });
        }
        else if (std::strcmp(cell.label, "resonator") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamCutoff, kx, ky))
                L.destJacks[PatchDestCutoff] = { kx - content->knobRadius - 12.0f, ky, PatchDestCutoff };
            if (knobCenter(kParamResonance, kx, ky))
                L.destJacks[PatchDestResonance] = { kx + content->knobRadius + 8.0f, ky, PatchDestResonance };
            if (knobCenter(kParamDrive, kx, ky))
                L.destJacks[PatchDestDrive] = { kx + content->knobRadius + 12.0f, ky, PatchDestDrive };
        }
        else if (std::strcmp(cell.label, "delay") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamDelayTime, kx, ky))
                L.destJacks[PatchDestDelayTime] = { kx - content->knobRadius - 12.0f, ky, PatchDestDelayTime };
            if (knobCenter(kParamDelayMix, kx, ky))
                L.destJacks[PatchDestDelayMix] = { kx + content->knobRadius + 8.0f, ky, PatchDestDelayMix };
        }
        else if (std::strcmp(cell.label, "chorus") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamChorusRate, kx, ky))
                L.destJacks[PatchDestChorusRate] = { kx - content->knobRadius - 12.0f, ky, PatchDestChorusRate };
            if (knobCenter(kParamChorusDepth, kx, ky))
                L.destJacks[PatchDestChorusDepth] = { kx + content->knobRadius + 8.0f, ky, PatchDestChorusDepth };
        }
        else if (std::strcmp(cell.label, "space") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamSpaceSize, kx, ky))
                L.destJacks[PatchDestSpaceSize] = { kx - content->knobRadius - 12.0f, ky, PatchDestSpaceSize };
        }
        else if (std::strcmp(cell.label, "grain") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamAge, kx, ky))
                L.destJacks[PatchDestAge] = { kx + content->knobRadius + 12.0f, ky, PatchDestAge };
            if (knobCenter(kParamNoise, kx, ky))
                L.destJacks[PatchDestNoise] = { kx - content->knobRadius - 12.0f, ky, PatchDestNoise };
        }
        else if (std::strcmp(cell.label, "modwheel") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamModWheelAmount, kx, ky))
                L.sourceJacks[PatchSrcModWheel] = { kx + content->knobRadius + 14.0f, ky, PatchSrcModWheel };
            if (knobCenter(kParamVelocityAmount, kx, ky))
                L.sourceJacks[PatchSrcVelocity] = { kx + content->knobRadius + 14.0f, ky, PatchSrcVelocity };
        }
        else if (std::strcmp(cell.label, "pitchbend") == 0)
        {
            float kx, ky;
            if (knobCenter(kParamPitchBendAmount, kx, ky))
                L.sourceJacks[PatchSrcPitchBend] = { kx + content->knobRadius + 14.0f, ky, PatchSrcPitchBend };
            if (knobCenter(kParamAftertouchAmount, kx, ky))
                L.sourceJacks[PatchSrcAftertouch] = { kx + content->knobRadius + 14.0f, ky, PatchSrcAftertouch };
        }
    }

    return L;
}

// -----------------------------------------------------------------------------------------------------------
// value mapping (generic - depends only on Params.hpp's ParamInfo)

inline float paramToNormalized(uint32_t param, float value) noexcept
{
    const ParamInfo& info = getParamInfo(param);
    float t;
    if (info.shape == ParamShape::Logarithmic)
    {
        const float lo = info.min > 0.0f ? info.min : 1e-6f;
        const float hi = info.max > lo ? info.max : lo * 1.0001f;
        const float v = value < lo ? lo : (value > hi ? hi : value);
        t = (float)(std::log(v / lo) / std::log(hi / lo));
    }
    else
    {
        t = (value - info.min) / (info.max - info.min);
    }
    return t < 0.0f ? 0.0f : (t > 1.0f ? 1.0f : t);
}

inline float normalizedToParam(uint32_t param, float t) noexcept
{
    const ParamInfo& info = getParamInfo(param);
    t = t < 0.0f ? 0.0f : (t > 1.0f ? 1.0f : t);
    if (info.shape == ParamShape::Logarithmic)
    {
        const float lo = info.min > 0.0f ? info.min : 1e-6f;
        const float hi = info.max > lo ? info.max : lo * 1.0001f;
        return lo * std::pow(hi / lo, t);
    }
    return info.min + (info.max - info.min) * t;
}

inline void formatParamValue(uint32_t index, float value, char* out, size_t outSize) noexcept
{
    if (index == kParamVoices)
    {
        std::snprintf(out, outSize, "%d", (int)(value + 0.5f));
        return;
    }
    if (index == kParamOscBOctave || index == kParamOscCOctave)
    {
        std::snprintf(out, outSize, "%+d", (int)(value + (value >= 0.0f ? 0.5f : -0.5f)));
        return;
    }
    if (index == kParamDelaySync)
    {
        static const char* kSyncLabels[8] = { "FREE", "1/1", "1/2", "1/4", "1/8", "1/16", "1/32", "1/64" };
        int idx = (int)(value + 0.5f);
        idx = idx < 0 ? 0 : (idx > 7 ? 7 : idx);
        std::snprintf(out, outSize, "%s", kSyncLabels[idx]);
        return;
    }

    const ParamInfo& info = getParamInfo(index);

    if (std::strcmp(info.unit, "Hz") == 0)
    {
        if (value >= 1000.0f)
            std::snprintf(out, outSize, "%.2fk", value / 1000.0);
        else
            std::snprintf(out, outSize, "%.2f", value);
    }
    else if (std::strcmp(info.unit, "ct") == 0)
    {
        std::snprintf(out, outSize, "%+.0fct", value);
    }
    else if (std::strcmp(info.unit, "st") == 0)
    {
        std::snprintf(out, outSize, "%+dst", (int)(value + (value >= 0.0f ? 0.5f : -0.5f)));
    }
    else if (std::strcmp(info.unit, "s") == 0)
    {
        if (value < 1.0f)
            std::snprintf(out, outSize, "%.0fms", value * 1000.0);
        else
            std::snprintf(out, outSize, "%.2fs", value);
    }
    else if (std::strcmp(info.unit, "ms") == 0)
    {
        std::snprintf(out, outSize, "%.0fms", value);
    }
    else
    {
        std::snprintf(out, outSize, "%.2f", value);
    }
}

// -----------------------------------------------------------------------------------------------------------
// drawing helpers

inline void setColor(cairo_t* cr, Color c, double a = 1.0) noexcept
{
    cairo_set_source_rgba(cr, c.r, c.g, c.b, a);
}

inline void roundedRect(cairo_t* cr, double x, double y, double w, double h, double r)
{
    cairo_new_sub_path(cr);
    cairo_arc(cr, x + w - r, y + r,     r, -M_PI_2, 0.0);
    cairo_arc(cr, x + w - r, y + h - r, r, 0.0,      M_PI_2);
    cairo_arc(cr, x + r,     y + h - r, r, M_PI_2,   M_PI);
    cairo_arc(cr, x + r,     y + r,     r, M_PI,     3.0 * M_PI_2);
    cairo_close_path(cr);
}

// cairo_show_text() leaves a dangling current point; if the next drawing call
// is cairo_arc()/cairo_line_to() without an explicit new subpath, cairo will
// implicitly connect from that stray point. Always reset the path after text.
inline void drawText(cairo_t* cr, const char* text, double x, double y)
{
    cairo_move_to(cr, x, y);
    cairo_show_text(cr, text);
    cairo_new_path(cr);
}

inline void centeredText(cairo_t* cr, const char* text, double cx, double cy)
{
    cairo_text_extents_t ext;
    cairo_text_extents(cr, text, &ext);
    drawText(cr, text, cx - ext.width / 2.0 - ext.x_bearing, cy - ext.height / 2.0 - ext.y_bearing);
}

inline void setFont(cairo_t* cr, double size, bool bold = true)
{
    cairo_select_font_face(cr, "sans-serif",
                            CAIRO_FONT_SLANT_NORMAL,
                            bold ? CAIRO_FONT_WEIGHT_BOLD : CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size(cr, size);
}

inline void setMonoFont(cairo_t* cr, double size, bool bold = false)
{
    cairo_select_font_face(cr, "monospace",
                            CAIRO_FONT_SLANT_NORMAL,
                            bold ? CAIRO_FONT_WEIGHT_BOLD : CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size(cr, size);
}

// -----------------------------------------------------------------------------------------------------------
// portrait image (lazy-loaded once from the embedded PNG bytes, cached)

struct PortraitReadState { const unsigned char* data; std::size_t len; std::size_t pos; };

inline cairo_status_t portraitReadFn(void* closure, unsigned char* out, unsigned int lenWanted)
{
    auto* st = (PortraitReadState*)closure;
    if (st->pos + lenWanted > st->len)
        return CAIRO_STATUS_READ_ERROR;
    std::memcpy(out, st->data + st->pos, lenWanted);
    st->pos += lenWanted;
    return CAIRO_STATUS_SUCCESS;
}

inline cairo_surface_t* portraitSurface()
{
    static cairo_surface_t* surface = nullptr;
    if (surface == nullptr)
    {
        PortraitReadState st{ kPortraitPng, kPortraitPngLen, 0 };
        surface = cairo_image_surface_create_from_png_stream(portraitReadFn, &st);
    }
    return surface;
}

// -----------------------------------------------------------------------------------------------------------
// paint

struct PaintState
{
    const float* values = nullptr;   // [kParamCount]
    int hoverKnob = -1;
    int dragKnob = -1;
    const bool* autoShowValue = nullptr; // [kParamCount]

    const char* presetName = "INIT";
    bool presetIsUnsaved = false;
    bool presetEditingName = false;
    const char* presetEditBuffer = "";
    int hoverPresetButton = -1; // 0=prev,1=next,2=save,3=delete, or -1
    bool presetDeleteEnabled = false;

    // patch cables
    int hoverSourceJack = -1;    // index into PatchSrc, or -1
    int hoverDestJack = -1;      // index into PatchDest, or -1
    bool dragging = false;
    bool dragFromSource = false; // true if the drag started on a source jack
    int dragIndex = -1;          // PatchSrc or PatchDest index being dragged from
    double dragCurX = 0.0, dragCurY = 0.0; // live cursor position while dragging
};

inline bool isPatched(const float* values, int src, int dest) noexcept
{
    const uint32_t index = kParamPatchFirst + (uint32_t)src * (uint32_t)kPatchNumDests + (uint32_t)dest;
    return values[index] > 0.5f;
}

inline Color patchSrcColor(int src) noexcept
{
    switch (src)
    {
    case PatchSrcDrift:     return Color{ 0.91, 0.58, 0.35 }; // warm amber
    case PatchSrcAmpEnv:    return Color{ 0.85, 0.35, 0.30 }; // red
    case PatchSrcFilterEnv: return Color{ 0.40, 0.60, 0.85 }; // steel blue
    case PatchSrcLfo:       return Color{ 0.80, 0.75, 0.30 }; // gold
    case PatchSrcModWheel:   return Color{ 0.35, 0.75, 0.65 }; // teal
    case PatchSrcPitchBend:  return Color{ 0.65, 0.45, 0.85 }; // violet
    case PatchSrcVelocity:   return Color{ 0.90, 0.75, 0.40 }; // sand
    case PatchSrcAftertouch:
    default:                 return Color{ 0.80, 0.40, 0.55 }; // rose
    }
}

inline void paintKnob(cairo_t* cr, const Knob& k, float value, bool hovered, bool dragging, bool autoShow)
{
    const float t = paramToNormalized(k.param, value);

    const double startAngle = M_PI * 0.75;
    const double sweep = M_PI * 1.5;
    const double valueAngle = startAngle + sweep * t;

    cairo_set_line_width(cr, 2.0);
    setColor(cr, kTextMain, 0.2);
    cairo_arc(cr, k.cx, k.cy, k.radius, startAngle, startAngle + sweep);
    cairo_stroke(cr);

    setColor(cr, k.accent, dragging ? 1.0 : (hovered ? 0.95 : 0.85));
    cairo_arc(cr, k.cx, k.cy, k.radius, startAngle, valueAngle);
    cairo_stroke(cr);

    setColor(cr, kKnobBody, 0.22);
    cairo_arc(cr, k.cx, k.cy, k.radius - 6.0, 0.0, 2.0 * M_PI);
    cairo_fill(cr);

    if (hovered || dragging)
    {
        setColor(cr, k.accent, 0.18);
        cairo_arc(cr, k.cx, k.cy, k.radius - 6.0, 0.0, 2.0 * M_PI);
        cairo_fill(cr);
    }

    setColor(cr, kTextMain);
    cairo_set_line_width(cr, 2.0);
    const double px = k.cx + std::cos(valueAngle) * (k.radius - 8.0);
    const double py = k.cy + std::sin(valueAngle) * (k.radius - 8.0);
    cairo_move_to(cr, k.cx, k.cy);
    cairo_line_to(cr, px, py);
    cairo_stroke(cr);

    setMonoFont(cr, 8.0);
    setColor(cr, kTextMain, 0.62);
    centeredText(cr, k.label, k.cx, k.cy + k.radius + 14.0);

    if (dragging || autoShow)
    {
        char buf[32];
        formatParamValue(k.param, value, buf, sizeof(buf));
        setMonoFont(cr, 11.0);
        setColor(cr, k.accent);
        centeredText(cr, buf, k.cx, k.cy - k.radius - 12.0);
    }
}

inline void paintButton(cairo_t* cr, const Button& b, bool hovered, bool enabled)
{
    roundedRect(cr, b.x, b.y, b.w, b.h, 3.0);
    setColor(cr, kBtnBg, enabled ? (hovered ? 1.0 : 0.85) : 0.4);
    cairo_fill_preserve(cr);
    setColor(cr, b.accent, enabled ? 1.0 : 0.35);
    cairo_set_line_width(cr, 1.2);
    cairo_stroke(cr);

    setMonoFont(cr, 10.5);
    setColor(cr, b.accent, enabled ? 1.0 : 0.35);
    centeredText(cr, b.label, b.x + b.w / 2.0, b.y + b.h / 2.0);
}

inline void paintPresetBar(cairo_t* cr, const PresetBarLayout& pb, const PaintState& state)
{
    paintButton(cr, pb.prev, state.hoverPresetButton == 0, true);
    paintButton(cr, pb.next, state.hoverPresetButton == 1, true);
    paintButton(cr, pb.save, state.hoverPresetButton == 2, true);
    paintButton(cr, pb.del,  state.hoverPresetButton == 3, state.presetDeleteEnabled);

    setMonoFont(cr, 12.0);
    if (state.presetEditingName)
    {
        char buf[40];
        std::snprintf(buf, sizeof(buf), "%s_", state.presetEditBuffer);
        setColor(cr, kTextMain);
        drawText(cr, buf, pb.nameX, pb.nameY + pb.nameH * 0.68);
    }
    else
    {
        setColor(cr, state.presetIsUnsaved ? kAccent : kTextMain, 0.85);
        char buf[40];
        std::snprintf(buf, sizeof(buf), "%s%s", state.presetName, state.presetIsUnsaved ? " *" : "");
        drawText(cr, buf, pb.nameX, pb.nameY + pb.nameH * 0.68);
    }
}

inline void paintVoronoiCell(cairo_t* cr, const VoronoiCellGeo& cell)
{
    cairo_save(cr);
    cairo_translate(cr, 0.0, kVoronoiHeaderHeight);

    cairo_new_path(cr);
    cairo_move_to(cr, cell.polygon[0].first, cell.polygon[0].second);
    for (size_t i = 1; i < cell.polygon.size(); ++i)
        cairo_line_to(cr, cell.polygon[i].first, cell.polygon[i].second);
    cairo_close_path(cr);

    setColor(cr, fromHex(cell.fillColor));
    cairo_fill(cr);

    cairo_restore(cr);
}

// the center cell (first in voronoiCells(), no tag) gets the portrait image
// instead of a flat fill - drawn "cover"-style (fills the polygon's bbox,
// cropping whichever axis overflows) then clipped to the polygon, over a
// flat fallback fill (cell.fillColor) in case the image is scaled down
// enough to no longer fully cover the polygon.
inline void paintPortraitCell(cairo_t* cr, const VoronoiCellGeo& cell)
{
    cairo_surface_t* img = portraitSurface();
    if (img == nullptr || cairo_surface_status(img) != CAIRO_STATUS_SUCCESS)
        return;

    cairo_save(cr);
    cairo_translate(cr, 0.0, kVoronoiHeaderHeight);

    cairo_new_path(cr);
    cairo_move_to(cr, cell.polygon[0].first, cell.polygon[0].second);
    for (size_t i = 1; i < cell.polygon.size(); ++i)
        cairo_line_to(cr, cell.polygon[i].first, cell.polygon[i].second);
    cairo_close_path(cr);
    setColor(cr, fromHex(cell.fillColor));
    cairo_fill_preserve(cr);
    cairo_clip(cr);

    const CellPolygonBounds b = boundsOf(cell);
    const double imgW = (double)cairo_image_surface_get_width(img);
    const double imgH = (double)cairo_image_surface_get_height(img);
    // shrunk 30% from a true cover-fit so the eye reads as a smaller motif
    // within the cell rather than filling it edge to edge - the fallback
    // fill above shows around it since it no longer fully covers the
    // polygon.
    const double scale = std::max((double)b.w / imgW, (double)b.h / imgH) * 0.7;
    const double drawW = imgW * scale, drawH = imgH * scale;
    const double offX = b.x + (b.w - drawW) * 0.5;
    const double offY = b.y + (b.h - drawH) * 0.5; // source image is already just the eye, roughly centered in its own frame

    cairo_translate(cr, offX, offY);
    cairo_scale(cr, scale, scale);
    cairo_set_source_surface(cr, img, 0.0, 0.0);
    cairo_paint(cr);

    cairo_restore(cr);
}

// -----------------------------------------------------------------------------------------------------------
// patch cables

inline void paintJack(cairo_t* cr, const Jack& j, bool active, bool hovered, Color color)
{
    cairo_arc(cr, j.cx, j.cy, kJackRadius, 0.0, 2.0 * M_PI);
    setColor(cr, kKnobBody, 0.55);
    cairo_fill_preserve(cr);
    setColor(cr, color, hovered ? 1.0 : 0.8);
    cairo_set_line_width(cr, hovered ? 2.5 : 1.6);
    cairo_stroke(cr);

    if (active)
    {
        setColor(cr, color, 0.95);
        cairo_arc(cr, j.cx, j.cy, kJackRadius * 0.42, 0.0, 2.0 * M_PI);
        cairo_fill(cr);
    }
}

// same curve math as paintCable() below, factored out so PhellipeUI.cpp can
// sample points along it for click-to-disconnect hit-testing without
// duplicating the sag formula.
inline void cablePointAt(double x0, double y0, double x1, double y1, double t, double& outX, double& outY) noexcept
{
    const double midX = (x0 + x1) * 0.5;
    const double midY = (y0 + y1) * 0.5;
    const double sag = std::clamp(std::fabs(x1 - x0) * 0.15, 8.0, 60.0);
    const double ctrlX = midX, ctrlY = midY + sag;

    const double c1x = x0 + (2.0 / 3.0) * (ctrlX - x0), c1y = y0 + (2.0 / 3.0) * (ctrlY - y0);
    const double c2x = x1 + (2.0 / 3.0) * (ctrlX - x1), c2y = y1 + (2.0 / 3.0) * (ctrlY - y1);

    const double u = 1.0 - t;
    outX = u*u*u*x0 + 3*u*u*t*c1x + 3*u*t*t*c2x + t*t*t*x1;
    outY = u*u*u*y0 + 3*u*u*t*c1y + 3*u*t*t*c2y + t*t*t*y1;
}

// a sagging (hanging) cable between two points - a quadratic Bezier (via
// cairo's cubic primitive) rather than true catenary physics: visually
// convincing, closed-form, no iterative solving needed. Sag is floored so
// even adjacent jacks visibly droop, and capped so the longest spans on the
// canvas don't sag off it.
//
// `voltage` (0..1, default 0 for the live in-progress drag cable, which
// carries no real signal yet) is the connection's current modulation level -
// see kParamMeterFirst in Params.hpp - and drives a Cardinal-style glow: a
// soft wide halo plus a lift toward white on the core stroke, both scaling
// with signal level, so a cable visibly "lights up" as its source moves.
inline void paintCable(cairo_t* cr, double x0, double y0, double x1, double y1, Color color, double alpha, double voltage = 0.0)
{
    const double midX = (x0 + x1) * 0.5;
    const double midY = (y0 + y1) * 0.5;
    const double sag = std::clamp(std::fabs(x1 - x0) * 0.15, 8.0, 60.0);
    const double ctrlX = midX, ctrlY = midY + sag;

    const double c1x = x0 + (2.0 / 3.0) * (ctrlX - x0), c1y = y0 + (2.0 / 3.0) * (ctrlY - y0);
    const double c2x = x1 + (2.0 / 3.0) * (ctrlX - x1), c2y = y1 + (2.0 / 3.0) * (ctrlY - y1);

    const double v = std::clamp(voltage, 0.0, 1.0);
    // most patch sources spend most of their time well under full-scale (an
    // attenuator below 1.0, an envelope that's not always at its peak, a
    // slow drift), so a linear voltage->brightness mapping stayed almost
    // invisible in practice; sqrt boosts the visible range for typical
    // signal levels while still reaching full brightness at v=1.
    const double vv = std::sqrt(v);

    if (v > 0.015)
    {
        cairo_move_to(cr, x0, y0);
        cairo_curve_to(cr, c1x, c1y, c2x, c2y, x1, y1);
        setColor(cr, color, alpha * vv * 0.55);
        cairo_set_line_width(cr, 6.0 + vv * 12.0);
        cairo_stroke(cr);
    }

    const double lift = vv * 0.7;
    const Color lit{ color.r + (1.0 - color.r) * lift, color.g + (1.0 - color.g) * lift, color.b + (1.0 - color.b) * lift };

    cairo_move_to(cr, x0, y0);
    cairo_curve_to(cr, c1x, c1y, c2x, c2y, x1, y1);
    setColor(cr, lit, alpha);
    cairo_set_line_width(cr, 3.5 + vv * 2.5);
    cairo_stroke(cr);
}

inline void paint(cairo_t* cr, const Layout& L, const PaintState& state)
{
    setColor(cr, kBg);
    cairo_paint(cr);

    // voronoi field
    bool first = true;
    for (const VoronoiCellGeo& cell : voronoiCells())
    {
        if (first) { paintPortraitCell(cr, cell); first = false; continue; }
        paintVoronoiCell(cr, cell);
    }

    // cell titles/subtitles
    cairo_save(cr);
    cairo_translate(cr, 0.0, kVoronoiHeaderHeight);
    for (const VoronoiCellGeo& cell : voronoiCells())
    {
        if (cell.label == nullptr)
            continue;
        const CellContent* content = nullptr;
        for (const CellContent& c : cellContents())
            if (std::strcmp(c.tag, cell.label) == 0) { content = &c; break; }
        if (content == nullptr)
            continue;

        const CellPolygonBounds b = boundsOf(cell);
        const float centerX = b.cx + content->dx;
        const float centerY = b.cy + content->dy;

        setFont(cr, content->titleSize);
        setColor(cr, kTextMain, 0.92);
        centeredText(cr, content->title, centerX, centerY - 34.0f);

        setMonoFont(cr, 8.5f);
        setColor(cr, kTextMain, 0.5);
        centeredText(cr, content->subtitle, centerX, centerY - 18.0f);

        // per-row sub-labels (e.g. CORE's "OSC B"/"OSC C"), drawn just above
        // their own knob row rather than the cell's main title/subtitle
        for (size_t r = 0; r < content->rows.size(); ++r)
        {
            if (content->rows[r].subLabel == nullptr)
                continue;
            const float rowY = centerY + 20.0f + content->rowSpacing * (float)r;
            const float rowCenterX = centerX + content->rowDxStep * (float)r;
            setMonoFont(cr, 8.5f, true);
            setColor(cr, kAccent, 0.75);
            centeredText(cr, content->rows[r].subLabel, rowCenterX, rowY - content->knobRadius - 16.0f);
        }
    }
    cairo_restore(cr);

    // header: wordmark + preset bar
    setFont(cr, 26.0);
    setColor(cr, kTextMain);
    drawText(cr, "PHELLIPE", 20.0, kVoronoiHeaderHeight * 0.62);

    setMonoFont(cr, 10.0);
    setColor(cr, kAccent, 0.85);
    drawText(cr, "DRONE SYNTHESIZER", 210.0, kVoronoiHeaderHeight * 0.62);

    paintPresetBar(cr, L.presetBar, state);

    // knobs
    for (size_t i = 0; i < L.knobs.size(); ++i)
    {
        const Knob& k = L.knobs[i];
        const bool autoShow = state.autoShowValue != nullptr && state.autoShowValue[k.param];
        paintKnob(cr, k, state.values[k.param], (int)i == state.hoverKnob, (int)i == state.dragKnob, autoShow);
    }

    // patch cables: connected cables first, then jacks on top of them, then
    // - topmost of all - the live cable being dragged, if any, so it's
    // always visible over other cables while in progress.
    for (int s = 0; s < (int)kPatchNumSources; ++s)
    {
        for (int d = 0; d < (int)kPatchNumDests; ++d)
        {
            if (!isPatched(state.values, s, d))
                continue;
            const Jack& sj = L.sourceJacks[(size_t)s];
            const Jack& dj = L.destJacks[(size_t)d];
            const double voltage = std::fabs((double)state.values[kParamMeterFirst + (uint32_t)s]);
            paintCable(cr, sj.cx, sj.cy, dj.cx, dj.cy, patchSrcColor(s), 0.8, voltage);
        }
    }

    for (size_t s = 0; s < L.sourceJacks.size(); ++s)
        paintJack(cr, L.sourceJacks[s], true, (int)s == state.hoverSourceJack, patchSrcColor((int)s));
    for (size_t d = 0; d < L.destJacks.size(); ++d)
    {
        bool connected = false;
        for (int s = 0; s < (int)kPatchNumSources; ++s)
            connected |= isPatched(state.values, s, (int)d);
        paintJack(cr, L.destJacks[d], connected, (int)d == state.hoverDestJack, kTextMain);
    }

    if (state.dragging)
    {
        const Jack& from = state.dragFromSource ? L.sourceJacks[(size_t)state.dragIndex]
                                                 : L.destJacks[(size_t)state.dragIndex];
        const Color color = state.dragFromSource ? patchSrcColor(state.dragIndex) : kTextMain;
        paintCable(cr, from.cx, from.cy, state.dragCurX, state.dragCurY, color, 0.9);
    }
}

} // namespace ui
} // namespace phellipe
