// Auto-generated by tools/gen_voronoi.py - do not hand-edit.
// Bounded Voronoi tessellation (scipy.spatial.Voronoi + mirror-clipping)
// of the 1200x790 voronoi field, seeded at the coordinates in that script.
#pragma once

#include <vector>
#include <utility>
#include <cstdint>

namespace phellipe {
namespace ui {

struct VoronoiCellGeo
{
    const char* label;    // nullptr for unlabeled filler cells
    uint32_t fillColor;   // 0xRRGGBB
    std::vector<std::pair<float,float>> polygon; // absolute px, voronoi-field-local (add headerOffsetY when drawing)
};

static constexpr float kVoronoiFieldWidth = 1200.0f;
static constexpr float kVoronoiFieldHeight = 790.0f;
static constexpr float kVoronoiHeaderHeight = 70.0f;

inline const std::vector<VoronoiCellGeo>& voronoiCells()
{
    static const std::vector<VoronoiCellGeo> cells = {
        { nullptr, 0xc97a4a, { {775.44f, 481.85f}, {676.77f, 228.12f}, {449.78f, 255.63f}, {409.48f, 329.95f}, {606.52f, 573.34f} } }, // Center
        { "core", 0x862a1e, { {409.48f, 329.95f}, {292.68f, 390.57f}, {185.62f, 347.75f}, {0.00f, 35.90f}, {0.00f, 0.00f}, {378.20f, 0.00f}, {449.78f, 255.63f} } }, // Core
        { "resonator", 0x16233b, { {794.94f, 128.12f}, {996.35f, 341.73f}, {1200.00f, 293.10f}, {1200.00f, 0.00f}, {825.76f, 0.00f} } }, // Resonator
        { "drift", 0x6b3a26, { {0.00f, 422.00f}, {185.62f, 347.75f}, {292.68f, 390.57f}, {262.93f, 532.93f}, {180.00f, 617.94f}, {0.00f, 586.44f} } }, // Drift
        { "grain", 0x4a1512, { {180.00f, 617.94f}, {180.00f, 790.00f}, {520.00f, 790.00f}, {262.93f, 532.93f} } }, // Grain
        { "space", 0x223a56, { {996.35f, 341.73f}, {890.56f, 500.41f}, {905.15f, 532.20f}, {1020.35f, 630.54f}, {1200.00f, 585.62f}, {1200.00f, 293.10f} } }, // Space
        { "modwheel", 0x1a3a34, { {776.25f, 790.00f}, {905.15f, 532.20f}, {1020.35f, 630.54f}, {1009.95f, 790.00f} } }, // Output
        { "delay", 0x7a4520, { {794.94f, 128.12f}, {825.76f, 0.00f}, {378.20f, 0.00f}, {449.78f, 255.63f}, {676.77f, 228.12f} } }, // FillA
        { "ampenv", 0x5c2818, { {606.52f, 573.34f}, {409.48f, 329.95f}, {292.68f, 390.57f}, {262.93f, 532.93f}, {520.00f, 790.00f}, {561.91f, 790.00f} } }, // FillB
        { "filterenv", 0x1a2c46, { {794.94f, 128.12f}, {676.77f, 228.12f}, {775.44f, 481.85f}, {890.56f, 500.41f}, {996.35f, 341.73f} } }, // FillC
        { "chorus", 0x2c4868, { {905.15f, 532.20f}, {776.25f, 790.00f}, {561.91f, 790.00f}, {606.52f, 573.34f}, {775.44f, 481.85f}, {890.56f, 500.41f} } }, // FillD
        { "lfo", 0x8a6a2a, { {0.00f, 790.00f}, {180.00f, 790.00f}, {180.00f, 617.94f}, {0.00f, 586.44f} } }, // FillE
        { "output", 0x8a5a35, { {1020.35f, 630.54f}, {1200.00f, 585.62f}, {1200.00f, 790.00f}, {1009.95f, 790.00f} } }, // FillF
        { "pitchbend", 0x2c1e3a, { {0.00f, 422.00f}, {185.62f, 347.75f}, {0.00f, 35.90f} } }, // FillG
    };
    return cells;
}

} // namespace ui
} // namespace phellipe
