import numpy as np
from scipy.spatial import Voronoi

W, H = 1200, 790
HEADER_H = 70

seeds = [
    # Center/Drift/FillA/FillG/Core nudged (from the original mockup seeds)
    # to grow Core ~30% - it now needs to fit 10 knobs (3 tuning oscillators)
    # instead of 4 - at the expense of Drift/FillA/FillG's territory.
    ("Center",    640, 400, None),
    ("Core",      225, 175, "core"),
    ("Resonator", 995, 165, "resonator"),
    ("Drift",      95, 500, "drift"),
    ("Grain",     300, 700, "grain"),
    ("Space",    1075, 500, "space"),
    ("Output",    900, 705, "output"),
    ("FillA",     600,  70, "delay"),
    ("FillB",     430, 570, "ampenv"),
    ("FillC",     820, 330, "filterenv"),
    ("FillD",     770, 640, "chorus"),
    ("FillE",      60, 700, "lfo"),
    ("FillF",    1130, 720, "modwheel"),
    ("FillG",      15, 300, "pitchbend"),
]

colors = {
    "Center":    "0xc97a4a",  # placeholder flat fallback behind the portrait image
    "Core":      "0x862a1e",
    "Resonator": "0x16233b",
    "Drift":     "0x6b3a26",
    "Grain":     "0x4a1512",
    "Space":     "0x223a56",
    "Output":    "0x8a5a35",
    "FillA":     "0x7a4520",  # DELAY
    "FillB":     "0x5c2818",  # AMP ENV
    "FillC":     "0x1a2c46",  # FILTER ENV
    "FillD":     "0x2c4868",  # CHORUS
    "FillE":     "0x8a6a2a",  # LFO
    "FillF":     "0x1a3a34",  # MOD WHEEL
    "FillG":     "0x2c1e3a",  # PITCH BEND
}

names = [s[0] for s in seeds]
pts = np.array([[s[1], s[2]] for s in seeds], dtype=float)

mirrors = [pts.copy()]
left = pts.copy(); left[:,0] = -pts[:,0]; mirrors.append(left)
right = pts.copy(); right[:,0] = 2*W - pts[:,0]; mirrors.append(right)
top = pts.copy(); top[:,1] = -pts[:,1]; mirrors.append(top)
bottom = pts.copy(); bottom[:,1] = 2*H - pts[:,1]; mirrors.append(bottom)
allpts = np.vstack(mirrors)

vor = Voronoi(allpts)

def polygon_for(i):
    region_index = vor.point_region[i]
    region = vor.regions[region_index]
    assert -1 not in region, f"unbounded region for {names[i]}"
    verts = [vor.vertices[v] for v in region]
    out = []
    for x, y in verts:
        x = min(max(x, 0), W)
        y = min(max(y, 0), H)
        out.append((x, y))
    return out

print("// Auto-generated by tools/gen_voronoi.py - do not hand-edit.")
print("// Bounded Voronoi tessellation (scipy.spatial.Voronoi + mirror-clipping)")
print(f"// of the {W}x{H} voronoi field, seeded at the coordinates in that script.")
print("#pragma once")
print()
print("#include <vector>")
print("#include <utility>")
print("#include <cstdint>")
print()
print("namespace phellipe {")
print("namespace ui {")
print()
print("struct VoronoiCellGeo")
print("{")
print("    const char* label;    // nullptr for unlabeled filler cells")
print("    uint32_t fillColor;   // 0xRRGGBB")
print("    std::vector<std::pair<float,float>> polygon; // absolute px, voronoi-field-local (add headerOffsetY when drawing)")
print("};")
print()
print(f"static constexpr float kVoronoiFieldWidth = {float(W)}f;")
print(f"static constexpr float kVoronoiFieldHeight = {float(H)}f;")
print(f"static constexpr float kVoronoiHeaderHeight = {float(HEADER_H)}f;")
print()
print("inline const std::vector<VoronoiCellGeo>& voronoiCells()")
print("{")
print("    static const std::vector<VoronoiCellGeo> cells = {")

for i, (name, sx, sy, tag) in enumerate(seeds):
    poly = polygon_for(i)
    pts_str = ", ".join(f"{{{x:.2f}f, {y:.2f}f}}" for x, y in poly)
    label = "nullptr" if tag is None else f'"{tag}"'
    print(f'        {{ {label}, {colors[name]}, {{ {pts_str} }} }}, // {name}')

print("    };")
print("    return cells;")
print("}")
print()
print("} // namespace ui")
print("} // namespace phellipe")
