/*
 * Phellipe - shared parameter definitions used by both the DSP plugin side
 * and the UI, so ranges/units/labels can't drift between the two.
 */

#pragma once

#include <cstdint>

namespace phellipe {

enum Params : uint32_t {
    kParamVoices = 0,
    kParamDetune,
    kParamSpread,
    kParamWave,
    kParamOscALevel,
    kParamOscBFree,
    kParamOscBOctave,
    kParamOscBSemi,
    kParamOscBWave,
    kParamOscBLevel,
    kParamOscCFree,
    kParamOscCOctave,
    kParamOscCSemi,
    kParamOscCWave,
    kParamOscCLevel,
    // full 6-way FM matrix between OSC A/B/C - see dsp/Voice.hpp's header
    // comment for the topology and why a full (potentially cyclic) matrix
    // is stable
    kParamFmAtoB,
    kParamFmAtoC,
    kParamFmBtoA,
    kParamFmBtoC,
    kParamFmCtoA,
    kParamFmCtoB,
    kParamCutoff,
    kParamResonance,
    kParamDrive,
    kParamDriftRate,
    kParamDriftDepth,
    kParamDriftChaos,
    kParamNoise,
    kParamGrain,
    kParamAge,
    kParamSpaceSize,
    kParamSpaceDecay,
    kParamSpaceMix,
    kParamVolume,
    kParamWidth,
    kParamAmpAttack,
    kParamAmpDecay,
    kParamAmpSustain,
    kParamAmpRelease,
    kParamFilterAttack,
    kParamFilterDecay,
    kParamFilterSustain,
    kParamFilterRelease,
    kParamDelayTime,
    kParamDelayFeedback,
    kParamDelayMix,
    kParamDelaySync,
    kParamChorusRate,
    kParamChorusDepth,
    kParamChorusMix,

    kParamLfoRate,
    kParamAmpEnvAmount,
    kParamFilterEnvAmount,
    kParamLfoAmount,
    kParamModWheelAmount,
    kParamPitchBendAmount,
    kParamVelocityAmount,
    kParamAftertouchAmount,

    // patch-cable "voltage" meters: one read-only output per source, updated
    // every audio block with that source's current attenuated value (the
    // same already-attenuated number summed into the patch matrix in
    // PhellipePlugin.cpp's run()) - lets the UI glow each cable by its live
    // signal level, Cardinal-style. Contiguous/source-major like the patch
    // matrix below, indexed the same way: kParamMeterFirst + src.
    kParamMeterFirst,
    kParamMeterDrift = kParamMeterFirst,
    kParamMeterAmpEnv,
    kParamMeterFilterEnv,
    kParamMeterLfo,
    kParamMeterModWheel,
    kParamMeterPitchBend,
    kParamMeterVelocity,
    kParamMeterAftertouch,

    // retro pixel scope: 32 read-only samples of the final mixed output
    // (post-tanh, mono-summed), captured at a fixed decimation so one full
    // buffer is one "sweep" - see PhellipePlugin.cpp's kScopeSize/
    // kScopeSweepSeconds. UI reads kParamScopeFirst+i left to right, no
    // read-offset to track since the write position wrapping back to 0 IS
    // the classic CRT-sweep-restart look. Contiguous, indexed the same way
    // as the meters/patch matrix above/below.
    kParamScopeFirst,
    kParamScope0 = kParamScopeFirst,
    kParamScope1,
    kParamScope2,
    kParamScope3,
    kParamScope4,
    kParamScope5,
    kParamScope6,
    kParamScope7,
    kParamScope8,
    kParamScope9,
    kParamScope10,
    kParamScope11,
    kParamScope12,
    kParamScope13,
    kParamScope14,
    kParamScope15,
    kParamScope16,
    kParamScope17,
    kParamScope18,
    kParamScope19,
    kParamScope20,
    kParamScope21,
    kParamScope22,
    kParamScope23,
    kParamScope24,
    kParamScope25,
    kParamScope26,
    kParamScope27,
    kParamScope28,
    kParamScope29,
    kParamScope30,
    kParamScope31,

    // the semi-modular patch matrix: 8 sources (Drift, AmpEnv, FilterEnv, Lfo,
    // ModWheel, PitchBend, Velocity, Aftertouch) x 15 destinations (Pitch,
    // Cutoff, Wave, DelayTime, ChorusRate, LfoRate, Age, OscBFree, OscCFree,
    // Resonance, Drive, ChorusDepth, SpaceSize, DelayMix, Noise), laid out
    // source-major and contiguous so PhellipePlugin.cpp can index into it
    // with plain (index - kParamPatchFirst) / 15 and % 15 arithmetic instead
    // of 120 switch cases. Keep this block's order in sync with the source
    // and destination enums documented in PhellipePlugin.cpp/ui/UIPainter.hpp.
    kParamPatchFirst,
    kParamPatchDriftPitch = kParamPatchFirst,
    kParamPatchDriftCutoff,
    kParamPatchDriftWave,
    kParamPatchDriftDelayTime,
    kParamPatchDriftChorusRate,
    kParamPatchDriftLfoRate,
    kParamPatchDriftAge,
    kParamPatchDriftOscBFree,
    kParamPatchDriftOscCFree,
    kParamPatchDriftResonance,
    kParamPatchDriftDrive,
    kParamPatchDriftChorusDepth,
    kParamPatchDriftSpaceSize,
    kParamPatchDriftDelayMix,
    kParamPatchDriftNoise,
    kParamPatchAmpEnvPitch,
    kParamPatchAmpEnvCutoff,
    kParamPatchAmpEnvWave,
    kParamPatchAmpEnvDelayTime,
    kParamPatchAmpEnvChorusRate,
    kParamPatchAmpEnvLfoRate,
    kParamPatchAmpEnvAge,
    kParamPatchAmpEnvOscBFree,
    kParamPatchAmpEnvOscCFree,
    kParamPatchAmpEnvResonance,
    kParamPatchAmpEnvDrive,
    kParamPatchAmpEnvChorusDepth,
    kParamPatchAmpEnvSpaceSize,
    kParamPatchAmpEnvDelayMix,
    kParamPatchAmpEnvNoise,
    kParamPatchFilterEnvPitch,
    kParamPatchFilterEnvCutoff,
    kParamPatchFilterEnvWave,
    kParamPatchFilterEnvDelayTime,
    kParamPatchFilterEnvChorusRate,
    kParamPatchFilterEnvLfoRate,
    kParamPatchFilterEnvAge,
    kParamPatchFilterEnvOscBFree,
    kParamPatchFilterEnvOscCFree,
    kParamPatchFilterEnvResonance,
    kParamPatchFilterEnvDrive,
    kParamPatchFilterEnvChorusDepth,
    kParamPatchFilterEnvSpaceSize,
    kParamPatchFilterEnvDelayMix,
    kParamPatchFilterEnvNoise,
    kParamPatchLfoPitch,
    kParamPatchLfoCutoff,
    kParamPatchLfoWave,
    kParamPatchLfoDelayTime,
    kParamPatchLfoChorusRate,
    kParamPatchLfoLfoRate,
    kParamPatchLfoAge,
    kParamPatchLfoOscBFree,
    kParamPatchLfoOscCFree,
    kParamPatchLfoResonance,
    kParamPatchLfoDrive,
    kParamPatchLfoChorusDepth,
    kParamPatchLfoSpaceSize,
    kParamPatchLfoDelayMix,
    kParamPatchLfoNoise,
    kParamPatchModWheelPitch,
    kParamPatchModWheelCutoff,
    kParamPatchModWheelWave,
    kParamPatchModWheelDelayTime,
    kParamPatchModWheelChorusRate,
    kParamPatchModWheelLfoRate,
    kParamPatchModWheelAge,
    kParamPatchModWheelOscBFree,
    kParamPatchModWheelOscCFree,
    kParamPatchModWheelResonance,
    kParamPatchModWheelDrive,
    kParamPatchModWheelChorusDepth,
    kParamPatchModWheelSpaceSize,
    kParamPatchModWheelDelayMix,
    kParamPatchModWheelNoise,
    kParamPatchPitchBendPitch,
    kParamPatchPitchBendCutoff,
    kParamPatchPitchBendWave,
    kParamPatchPitchBendDelayTime,
    kParamPatchPitchBendChorusRate,
    kParamPatchPitchBendLfoRate,
    kParamPatchPitchBendAge,
    kParamPatchPitchBendOscBFree,
    kParamPatchPitchBendOscCFree,
    kParamPatchPitchBendResonance,
    kParamPatchPitchBendDrive,
    kParamPatchPitchBendChorusDepth,
    kParamPatchPitchBendSpaceSize,
    kParamPatchPitchBendDelayMix,
    kParamPatchPitchBendNoise,
    kParamPatchVelocityPitch,
    kParamPatchVelocityCutoff,
    kParamPatchVelocityWave,
    kParamPatchVelocityDelayTime,
    kParamPatchVelocityChorusRate,
    kParamPatchVelocityLfoRate,
    kParamPatchVelocityAge,
    kParamPatchVelocityOscBFree,
    kParamPatchVelocityOscCFree,
    kParamPatchVelocityResonance,
    kParamPatchVelocityDrive,
    kParamPatchVelocityChorusDepth,
    kParamPatchVelocitySpaceSize,
    kParamPatchVelocityDelayMix,
    kParamPatchVelocityNoise,
    kParamPatchAftertouchPitch,
    kParamPatchAftertouchCutoff,
    kParamPatchAftertouchWave,
    kParamPatchAftertouchDelayTime,
    kParamPatchAftertouchChorusRate,
    kParamPatchAftertouchLfoRate,
    kParamPatchAftertouchAge,
    kParamPatchAftertouchOscBFree,
    kParamPatchAftertouchOscCFree,
    kParamPatchAftertouchResonance,
    kParamPatchAftertouchDrive,
    kParamPatchAftertouchChorusDepth,
    kParamPatchAftertouchSpaceSize,
    kParamPatchAftertouchDelayMix,
    kParamPatchAftertouchNoise,

    kParamCount
};

enum class ParamShape { Linear, Logarithmic, Boolean };

struct ParamInfo
{
    const char* name;
    const char* symbol;
    const char* unit;
    float min;
    float max;
    float def;
    ParamShape shape;
};

inline const ParamInfo& getParamInfo(uint32_t index) noexcept
{
    static constexpr ParamInfo table[kParamCount] = {
        { "Voices",     "voices",      "",   1.0f,     7.0f,     3.0f,   ParamShape::Linear },
        { "Detune",     "detune",      "ct", 0.0f,    50.0f,    12.0f,   ParamShape::Linear },
        { "Spread",     "spread",      "",   0.0f,     1.0f,     0.5f,   ParamShape::Linear },
        { "Wave",       "wave",        "",   0.0f,     1.0f,     0.3f,   ParamShape::Linear },
        { "A Level",    "osc_a_level", "",   0.0f,     1.0f,     1.0f,   ParamShape::Linear },
        { "B Free",     "osc_b_free",  "ct", -50.0f,   50.0f,    0.0f,   ParamShape::Linear },
        { "B Octave",   "osc_b_octave","",   -2.0f,     2.0f,    0.0f,   ParamShape::Linear },
        { "B Semi",     "osc_b_semi",  "st", -12.0f,   12.0f,    0.0f,   ParamShape::Linear },
        { "B Wave",     "osc_b_wave",  "",    0.0f,     1.0f,    0.3f,   ParamShape::Linear },
        { "B Level",    "osc_b_level", "",    0.0f,     1.0f,    1.0f,   ParamShape::Linear },
        { "C Free",     "osc_c_free",  "ct", -50.0f,   50.0f,    0.0f,   ParamShape::Linear },
        { "C Octave",   "osc_c_octave","",   -2.0f,     2.0f,    0.0f,   ParamShape::Linear },
        { "C Semi",     "osc_c_semi",  "st", -12.0f,   12.0f,    0.0f,   ParamShape::Linear },
        { "C Wave",     "osc_c_wave",  "",    0.0f,     1.0f,    0.3f,   ParamShape::Linear },
        { "C Level",    "osc_c_level", "",    0.0f,     1.0f,    1.0f,   ParamShape::Linear },
        { "FM A->B",    "fm_a_to_b",   "",    0.0f,     1.0f,    0.0f,   ParamShape::Linear },
        { "FM A->C",    "fm_a_to_c",   "",    0.0f,     1.0f,    0.0f,   ParamShape::Linear },
        { "FM B->A",    "fm_b_to_a",   "",    0.0f,     1.0f,    0.0f,   ParamShape::Linear },
        { "FM B->C",    "fm_b_to_c",   "",    0.0f,     1.0f,    0.0f,   ParamShape::Linear },
        { "FM C->A",    "fm_c_to_a",   "",    0.0f,     1.0f,    0.0f,   ParamShape::Linear },
        { "FM C->B",    "fm_c_to_b",   "",    0.0f,     1.0f,    0.0f,   ParamShape::Linear },
        { "Cutoff",     "cutoff",      "Hz", 20.0f, 20000.0f, 1800.0f,   ParamShape::Logarithmic },
        { "Reso",       "resonance",   "",   0.0f,     1.0f,     0.2f,   ParamShape::Linear },
        { "Drive",      "drive",       "",   0.0f,     1.0f,     0.0f,   ParamShape::Linear },
        { "Rate",       "drift_rate",  "Hz", 0.01f,    2.0f,    0.15f,   ParamShape::Logarithmic },
        { "Depth",      "drift_depth", "",   0.0f,     1.0f,     0.3f,   ParamShape::Linear },
        { "Chaos",      "drift_chaos", "",   0.0f,     1.0f,     0.2f,   ParamShape::Linear },
        { "Noise",      "noise",       "",   0.0f,     1.0f,     0.0f,   ParamShape::Linear },
        { "Grain",      "grain",       "",   0.0f,     1.0f,     0.0f,   ParamShape::Linear },
        { "Age",        "age",         "",   0.0f,     1.0f,     0.0f,   ParamShape::Linear },
        { "Size",       "space_size",  "",   0.0f,     1.0f,     0.5f,   ParamShape::Linear },
        { "Decay",      "space_decay", "",   0.0f,     1.0f,     0.5f,   ParamShape::Linear },
        { "Mix",        "space_mix",   "",   0.0f,     1.0f,     0.3f,   ParamShape::Linear },
        { "Volume",     "volume",      "",   0.0f,     1.0f,    0.92f,   ParamShape::Linear },
        { "Width",      "width",       "",   0.0f,     1.0f,    0.75f,   ParamShape::Linear },
        { "Amp Attack",   "amp_attack",     "s", 0.001f, 5.0f, 0.4f,  ParamShape::Logarithmic },
        { "Amp Decay",    "amp_decay",      "s", 0.001f, 5.0f, 0.3f,  ParamShape::Logarithmic },
        { "Amp Sustain",  "amp_sustain",    "",  0.0f,   1.0f, 1.0f,  ParamShape::Linear },
        { "Amp Release",  "amp_release",    "s", 0.001f, 8.0f, 0.8f,  ParamShape::Logarithmic },
        { "Filt Attack",  "filter_attack",  "s", 0.001f, 5.0f, 0.05f, ParamShape::Logarithmic },
        { "Filt Decay",   "filter_decay",   "s", 0.001f, 5.0f, 0.5f,  ParamShape::Logarithmic },
        { "Filt Sustain", "filter_sustain", "",  0.0f,   1.0f, 0.0f,  ParamShape::Linear },
        { "Filt Release", "filter_release", "s", 0.001f, 8.0f, 0.3f,  ParamShape::Logarithmic },
        { "Delay Time",     "delay_time",     "ms", 20.0f, 1200.0f, 350.0f, ParamShape::Logarithmic },
        { "Delay Feedback", "delay_feedback", "",   0.0f,    1.0f,   0.35f, ParamShape::Linear },
        { "Delay Mix",      "delay_mix",      "",   0.0f,    1.0f,   0.25f, ParamShape::Linear },
        // 0 = Free (use Delay Time), 1..7 = 1/1, 1/2, 1/4, 1/8, 1/16, 1/32, 1/64
        { "Delay Sync",     "delay_sync",     "",   0.0f,    7.0f,   0.0f,  ParamShape::Linear },
        { "Chorus Rate",    "chorus_rate",    "Hz", 0.05f,   3.0f,   0.3f,  ParamShape::Logarithmic },
        { "Chorus Depth",   "chorus_depth",   "",   0.0f,    1.0f,   0.4f,  ParamShape::Linear },
        { "Chorus Mix",     "chorus_mix",     "",   0.0f,    1.0f,   0.3f,  ParamShape::Linear },

        { "LFO Rate",          "lfo_rate",          "Hz", 0.05f, 10.0f, 1.0f,    ParamShape::Logarithmic },
        { "Amp Env Amount",    "ampenv_amount",     "",   0.0f,  1.0f,  0.5f,    ParamShape::Linear },
        { "Filter Env Amount", "filterenv_amount",  "",   0.0f,  1.0f,  0.7f,    ParamShape::Linear },
        { "LFO Amount",        "lfo_amount",        "",   0.0f,  1.0f,  0.5f,    ParamShape::Linear },
        { "Mod Wheel Amount",  "modwheel_amount",   "",   0.0f,  1.0f,  0.5f,    ParamShape::Linear },
        // default gives a real synth-style pitch bend (~2 semitones at full
        // wheel deflection: 0.1667 * kPitchModSemitones(12) = 2) rather than
        // the subtle "just another modulator" depth other sources default to
        { "Pitch Bend Amount", "pitchbend_amount",  "",   0.0f,  1.0f,  0.1667f, ParamShape::Linear },
        { "Velocity Amount",   "velocity_amount",   "",   0.0f,  1.0f,  0.5f,    ParamShape::Linear },
        { "Aftertouch Amount", "aftertouch_amount", "",   0.0f,  1.0f,  0.5f,    ParamShape::Linear },

        // patch-cable voltage meters - read-only, see the enum comment above
        { "Drift Meter",      "meter_drift",      "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },
        { "Amp Env Meter",    "meter_ampenv",     "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },
        { "Filter Env Meter", "meter_filterenv",  "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },
        { "LFO Meter",        "meter_lfo",        "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },
        { "Mod Wheel Meter",  "meter_modwheel",   "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },
        { "Pitch Bend Meter", "meter_pitchbend",  "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },
        { "Velocity Meter",   "meter_velocity",   "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },
        { "Aftertouch Meter", "meter_aftertouch", "", -1.0f, 1.0f, 0.0f, ParamShape::Linear },

        // retro pixel scope - read-only, see the enum comment above
        { "Scope 0",  "scope_0",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 1",  "scope_1",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 2",  "scope_2",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 3",  "scope_3",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 4",  "scope_4",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 5",  "scope_5",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 6",  "scope_6",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 7",  "scope_7",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 8",  "scope_8",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 9",  "scope_9",    "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 10", "scope_10",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 11", "scope_11",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 12", "scope_12",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 13", "scope_13",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 14", "scope_14",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 15", "scope_15",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 16", "scope_16",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 17", "scope_17",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 18", "scope_18",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 19", "scope_19",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 20", "scope_20",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 21", "scope_21",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 22", "scope_22",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 23", "scope_23",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 24", "scope_24",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 25", "scope_25",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 26", "scope_26",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 27", "scope_27",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 28", "scope_28",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 29", "scope_29",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 30", "scope_30",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },
        { "Scope 31", "scope_31",   "",   -1.0f,  1.0f,  0.0f,    ParamShape::Linear },

        // patch matrix - see the enum comment above for the source-major/
        // 15-wide layout. Defaults: all off except the three that reproduce
        // standard synth behavior out of the box - drift/filter-env -> cutoff
        // (the plugin's original hardwired coloration) and pitch bend -> pitch
        // (so the pitch wheel just works, as requested).
        { "Drift->Pitch",       "patch_drift_pitch",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Cutoff",      "patch_drift_cutoff",        "", 0.0f, 1.0f, 1.0f, ParamShape::Boolean },
        { "Drift->Wave",        "patch_drift_wave",          "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Delay",       "patch_drift_delaytime",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Chorus",      "patch_drift_chorusrate",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->LFO Rate",    "patch_drift_lforate",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Age",         "patch_drift_age",           "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->OscB Free",   "patch_drift_oscbfree",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->OscC Free",   "patch_drift_osccfree",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Resonance",   "patch_drift_resonance",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Drive",       "patch_drift_drive",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Chorus Depth","patch_drift_chorusdepth",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Space Size",  "patch_drift_spacesize",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Delay Mix",   "patch_drift_delaymix",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Drift->Noise",       "patch_drift_noise",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Pitch",      "patch_ampenv_pitch",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Cutoff",     "patch_ampenv_cutoff",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Wave",       "patch_ampenv_wave",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Delay",      "patch_ampenv_delaytime",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Chorus",     "patch_ampenv_chorusrate",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->LFO Rate",   "patch_ampenv_lforate",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Age",        "patch_ampenv_age",          "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->OscB Free",  "patch_ampenv_oscbfree",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->OscC Free",  "patch_ampenv_osccfree",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Resonance",  "patch_ampenv_resonance",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Drive",      "patch_ampenv_drive",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Chorus Depth","patch_ampenv_chorusdepth", "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Space Size", "patch_ampenv_spacesize",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Delay Mix",  "patch_ampenv_delaymix",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "AmpEnv->Noise",      "patch_ampenv_noise",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Pitch",     "patch_filterenv_pitch",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Cutoff",    "patch_filterenv_cutoff",    "", 0.0f, 1.0f, 1.0f, ParamShape::Boolean },
        { "FiltEnv->Wave",      "patch_filterenv_wave",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Delay",     "patch_filterenv_delaytime", "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Chorus",    "patch_filterenv_chorusrate","", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->LFO Rate",  "patch_filterenv_lforate",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Age",       "patch_filterenv_age",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->OscB Free", "patch_filterenv_oscbfree",  "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->OscC Free", "patch_filterenv_osccfree",  "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Resonance", "patch_filterenv_resonance", "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Drive",     "patch_filterenv_drive",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Chorus Depth","patch_filterenv_chorusdepth", "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Space Size","patch_filterenv_spacesize", "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Delay Mix", "patch_filterenv_delaymix",  "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "FiltEnv->Noise",     "patch_filterenv_noise",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Pitch",         "patch_lfo_pitch",           "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Cutoff",        "patch_lfo_cutoff",          "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Wave",          "patch_lfo_wave",            "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Delay",         "patch_lfo_delaytime",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Chorus",        "patch_lfo_chorusrate",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->LFO Rate",      "patch_lfo_lforate",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Age",           "patch_lfo_age",             "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->OscB Free",     "patch_lfo_oscbfree",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->OscC Free",     "patch_lfo_osccfree",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Resonance",     "patch_lfo_resonance",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Drive",         "patch_lfo_drive",           "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Chorus Depth",  "patch_lfo_chorusdepth",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Space Size",    "patch_lfo_spacesize",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Delay Mix",     "patch_lfo_delaymix",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "LFO->Noise",         "patch_lfo_noise",           "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Pitch",       "patch_modwheel_pitch",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Cutoff",      "patch_modwheel_cutoff",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Wave",        "patch_modwheel_wave",          "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Delay",       "patch_modwheel_delaytime",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Chorus",      "patch_modwheel_chorusrate",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->LFO Rate",    "patch_modwheel_lforate",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Age",         "patch_modwheel_age",           "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->OscB Free",   "patch_modwheel_oscbfree",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->OscC Free",   "patch_modwheel_osccfree",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Resonance",   "patch_modwheel_resonance",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Drive",       "patch_modwheel_drive",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Chorus Depth","patch_modwheel_chorusdepth",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Space Size",  "patch_modwheel_spacesize",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Delay Mix",   "patch_modwheel_delaymix",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "ModWheel->Noise",       "patch_modwheel_noise",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Pitch",      "patch_pitchbend_pitch",        "", 0.0f, 1.0f, 1.0f, ParamShape::Boolean },
        { "PitchBend->Cutoff",     "patch_pitchbend_cutoff",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Wave",       "patch_pitchbend_wave",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Delay",      "patch_pitchbend_delaytime",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Chorus",     "patch_pitchbend_chorusrate",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->LFO Rate",   "patch_pitchbend_lforate",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Age",        "patch_pitchbend_age",          "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->OscB Free",  "patch_pitchbend_oscbfree",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->OscC Free",  "patch_pitchbend_osccfree",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Resonance",  "patch_pitchbend_resonance",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Drive",      "patch_pitchbend_drive",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Chorus Depth","patch_pitchbend_chorusdepth", "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Space Size", "patch_pitchbend_spacesize",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Delay Mix",  "patch_pitchbend_delaymix",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "PitchBend->Noise",      "patch_pitchbend_noise",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Pitch",       "patch_velocity_pitch",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Cutoff",      "patch_velocity_cutoff",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Wave",        "patch_velocity_wave",          "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Delay",       "patch_velocity_delaytime",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Chorus",      "patch_velocity_chorusrate",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->LFO Rate",    "patch_velocity_lforate",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Age",         "patch_velocity_age",           "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->OscB Free",   "patch_velocity_oscbfree",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->OscC Free",   "patch_velocity_osccfree",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Resonance",   "patch_velocity_resonance",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Drive",       "patch_velocity_drive",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Chorus Depth","patch_velocity_chorusdepth",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Space Size",  "patch_velocity_spacesize",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Delay Mix",   "patch_velocity_delaymix",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Velocity->Noise",       "patch_velocity_noise",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Pitch",     "patch_aftertouch_pitch",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Cutoff",    "patch_aftertouch_cutoff",      "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Wave",      "patch_aftertouch_wave",        "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Delay",     "patch_aftertouch_delaytime",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Chorus",    "patch_aftertouch_chorusrate",  "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->LFO Rate",  "patch_aftertouch_lforate",     "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Age",       "patch_aftertouch_age",         "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->OscB Free", "patch_aftertouch_oscbfree",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->OscC Free", "patch_aftertouch_osccfree",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Resonance", "patch_aftertouch_resonance",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Drive",     "patch_aftertouch_drive",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Chorus Depth","patch_aftertouch_chorusdepth","", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Space Size","patch_aftertouch_spacesize",   "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Delay Mix", "patch_aftertouch_delaymix",    "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
        { "Aftertouch->Noise",     "patch_aftertouch_noise",       "", 0.0f, 1.0f, 0.0f, ParamShape::Boolean },
    };
    return table[index];
}

} // namespace phellipe
